# Generated by Django 4.0 on 2022-11-03 06:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_productgallery_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=512, validators=[django.core.validators.MaxLengthValidator(512, message='Maximum value exceeded')]),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='subject',
            field=models.CharField(blank=True, max_length=128, validators=[django.core.validators.MaxLengthValidator(128, message='Maximum value exceeded')]),
        ),
    ]
