# Generated by Django 4.0 on 2022-11-03 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_reviewrating_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='subject',
            field=models.CharField(blank=True, max_length=128, validators=[django.core.validators.MaxLengthValidator(128, message='Maximum length exceeded')]),
        ),
    ]
