# Generated by Django 4.0 on 2022-11-09 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_reviewrating_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
